### PR TITLE
GH4: Bump dependencies to reduce Cake warnings

### LINKED ISSUE #4: Bump dependencies to reduce Cake warnings
PR incoming...

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #4 

Note: [tools/packages.config](https://github.com/gitfool/Cake.DotNetTool.Module/blob/0570ca258f2cdf78a16b4ec4c6aea4c50f07d499/tools/packages.config#L3) limited to `Cake` 0.32.1 to avoid current issues with `Cake.Recipe`.

### CODE REVIEW

**Comment by gitfool** [comment]
@gep13 this built locally for me so I'm guessing the failure is due to extra steps done for AppVeyor builds.

**Comment by gep13** [comment]
@gitfool re-building this now, and I will review once the CI finishes.

**Comment by gep13** [comment]
@gitfool also, what are the current issues with Cake.Recipe?  Have you opened an issue there? (**NOTE:** I haven't checked yet).

**Comment by gep13** [comment]
@gitfool your changes have been merged, thanks for your contribution 👍

**Comment by gep13** [comment]
@gitfool

**Pull request merged**
